version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nlp-api-dev"
s3_bucket = "codebuild-nl"
s3_prefix = "nlp-api-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

