version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nlp-api"
s3_bucket = "serverless-application-model-nl"
s3_prefix = "nlp-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
